import image1 from "../assets/LocationImages/GradskiMuzej.jpg";
import image2 from "../assets/LocationImages/RostiljKodJonuza.jpg";
import image3 from "../assets/LocationImages/KulturniCentar.jpg";
import image4 from "../assets/LocationImages/RostiljKodDzekice.jpg";
import image5 from "../assets/LocationImages/DunjaCaffe.jpg";
import image6 from "../assets/LocationImages/HotelVrbak.jpg";
import image7 from "../assets/LocationImages/firenca.jpg";
import image8 from "../assets/LocationImages/SvePodSac.jpg";
import image9 from "../assets/LocationImages/Rile.jpg";
import image10 from "../assets/LocationImages/MamaMantija.jpg";
import image11 from "../assets/LocationImages/Gimnazija.jpg";
import image12 from "../assets/LocationImages/DUNP.jpg";
import image13 from "../assets/LocationImages/TehnickaSkola.jpg";
import image14 from "../assets/LocationImages/OsnovnaSkolaJovan.jpg";
import image15 from "../assets/LocationImages/AltunAlem.png";
import image16 from "../assets/LocationImages/Bolnica.jpg";
import image17 from "../assets/LocationImages/DohaRestoran.jpg";
import image18 from "../assets/LocationImages/Pijaca.jpg";
import image19 from "../assets/LocationImages/MotelDar.jpg";
import image20 from "../assets/LocationImages/Lidl.jpg";
import image21 from "../assets/LocationImages/PrenocisteDionis.jpg";
import image22 from "../assets/LocationImages/ApartmanFilip.jpg";
import image23 from "../assets/LocationImages/DjurdjeviStupovi.jpg";
import image24 from "../assets/LocationImages/HotelDragulj.jpg";
import image25 from "../assets/LocationImages/HadziMehova.jpg";
import image26 from "../assets/LocationImages/StariRas.jpg";
import image27 from "../assets/LocationImages/StariRasPecina.png";
import image28 from "../assets/LocationImages/Sopocani.jpg";
import image29 from "../assets/LocationImages/CrkvaPetra.jpg";
import image30 from "../assets/LocationImages/DrumPanorama.jpg";
import image31 from "../assets/LocationImages/JYSK.jpg";
import image32 from "../assets/LocationImages/DEICHMANN.jpg";
import image33 from "../assets/LocationImages/DallasNamestaj.jpg";
import image34 from "../assets/LocationImages/EmrovicRaj.JPG";
import image35 from "../assets/LocationImages/AquaSpa.jpg";
import image36 from "../assets/LocationImages/StaraBanja.jpg";
import image37 from "../assets/LocationImages/youmart.jpg";

export const MarkerLocations = [
	{
		location: [43.14163535508256, 20.51813593460599],
		name: "Muzej Ras",
		text: "Museum",
		image: image1,
		category: "Culture",
		saved: false,
		address: "Stevana Nemanje 20, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.141031073656954, 20.517888175811795],
		name: "Rostilj kod Jonuza",
		text: "Grill: 500-1000 RSD",
		image: image2,
		category: "Restaurant",
		saved: false,
		address: "28. novembra 12, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.140851580653376, 20.518408411726277],
		name: "Kulturni centar NP",
		text: "Cultural center",
		image: image3,
		category: "Culture",
		saved: false,
		address: "Stevana Nemanje 2, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.142967705577014, 20.520869959291918],
		name: "Rostilj kod Dzekice",
		text: "Grill",
		image: image4,
		category: "Restaurant",
		saved: false,
		address: "8 mart 66, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.14358255773858, 20.519195018949517],
		name: "Dunja Caffe",
		text: "Caffe&Food",
		image: image5,
		category: "Restaurant",
		saved: false,
		address: "Stevana Nemanje, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.1405537817087, 20.516479742809068],
		name: "Hotel Vrbak",
		text: "Hotel",
		image: image6,
		category: "Hotel",
		saved: false,
		address: "Kej 37. sandžačke divizije 2, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.14034882150852, 20.515179323103588],
		name: "Firenca 22 Restoran",
		text: "Restaurant",
		image: image7,
		category: "Restaurant",
		saved: false,
		address: "Kej 37. sandžačke divizije, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.1395441563386, 20.51839396027088],
		name: "SVE POD SAČ",
		text: "Local food",
		image: image8,
		category: "Restaurant",
		saved: false,
		address: "1. Maj 16, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.13918736745644, 20.518633237462655],
		name: "Cevabdzinica Rile",
		text: "Grill",
		image: image9,
		category: "Restaurant",
		saved: false,
		address: "1. Maj 16, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.13885335044584, 20.51862283410649],
		name: "Mama Mantija",
		text: "Local food",
		image: image10,
		category: "Restaurant",
		saved: false,
		address: "1. Maj 16, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.13829918181484, 20.5199544637667],
		name: "Gimnazija",
		text: "High School",
		image: image11,
		category: "Other",
		saved: false,
		address: "Vuka Karadžića, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.13836750424376, 20.521161253081726],
		name: "Drzavni Univerzitet Novi Pazar",
		text: "University",
		image: image12,
		category: "Other",
		saved: false,
		address: "Vuka Karadžića, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.1378968370688, 20.521504563851146],
		name: "Tehnička škola 'Izudin Šušević' Novi Pazar",
		text: "High School",
		image: image13,
		category: "Other",
		saved: false,
		address: "Vuka Karadžića, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.13793479423294, 20.51995446378271],
		name: "Osnovna skola 'Jovan Jovanovic Zmaj'",
		text: "Primary School",
		image: image14,
		category: "Other",
		saved: false,
		address: "Vuka Karadžića, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.13676098839355, 20.518613738823863],
		name: "Altum Alem Mosque",
		text: "Mosque",
		image: image15,
		category: "Culture",
		saved: false,
		address: "1. maja, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.133875391510756, 20.511535063127567],
		name: "Opsta bolnica Novi Pazar",
		text: "Hospital",
		image: image16,
		category: "Other",
		saved: false,
		address: "Generala Živkovića, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.14318756376092, 20.51554898387914],
		name: "DOHA Restourant",
		text: "Restourant",
		image: image17,
		category: "Restaurant",
		saved: false,
		address: "28. novembra 54, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.1466609543503, 20.52670885897865],
		name: "Velika robna pijaca Novi Pazar",
		text: "Shopping mall",
		image: image18,
		category: "Other",
		saved: false,
		address: "Save Kovačevića, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.15064656914682, 20.530116652883855],
		name: "Motel & Restaurant Dar",
		text: "Motel",
		image: image19,
		category: "Hotel",
		saved: false,
		address: "Save Kovačevića, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.15183924782702, 20.526512339977323],
		name: "Lidl",
		text: "Supermarket",
		image: image20,
		category: "Other",
		saved: false,
		address: "Dimitrija Tucovića 6A, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.152479846861944, 20.522740564125947],
		name: "Restoran Dionis-prenoćišta",
		text: "Motel",
		image: image21,
		category: "Hotel",
		saved: false,
		address: "Miodraga Jovanovića 2, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.15428034491694, 20.52411878731419],
		name: "Apartment Filip",
		text: "Hotel",
		image: image22,
		category: "Hotel",
		saved: false,
		address: "Stevana Nemanje 230, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.16878093202005, 20.497926158748477],
		name: "Đurđevi Stupovi Monastery",
		text: "Manastir",
		image: image23,
		category: "Culture",
		saved: false,
		address: "5F8X+C3, Ђурђеви ступови, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.141975975067794, 20.456181008415147],
		name: "Hotel Dragulj",
		text: "Hotel",
		image: image24,
		category: "Hotel",
		saved: false,
		address: "Dojevice bb, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.12811338414333, 20.494976690006773],
		name: "Hadzi Mehova Dzamija",
		text: "Mosque",
		image: image25,
		category: "Culture",
		saved: false,
		address: "Hadži-Mehova džamija, Ive Andrića, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.1287872042997, 20.416074686603302],
		name: "Stari Ras",
		text: "Cultural Destination",
		image: image26,
		category: "Culture",
		saved: false,
		address: "203, Sebečevo",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.12794353610048, 20.417146838399542],
		name: "Stari Ras Cave",
		text: "Cave",
		image: image27,
		category: "Culture",
		saved: false,
		address: "203, Sebečevo",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.11827361718015, 20.37398041099268],
		name: "Sopocani Monastery",
		text: "Manastir",
		image: image28,
		category: "Culture",
		saved: false,
		address: "204, Doljani",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.161497448389206, 20.527571586039794],
		name: "Church of the Holy Apostles Peter and Paul",
		text: "Crkva",
		image: image29,
		category: "Culture",
		saved: false,
		address: "Slava Raškovića 147, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.141358822653764, 20.504580434523824],
		name: "Drum Panorama - Šoping centar",
		text: "Shopping mall",
		image: image30,
		category: "Other",
		saved: false,
		address: "Rifata Burdževića 209b, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.14100122832225, 20.523698024856966],
		name: "JYSK Novi Pazar",
		text: "Furniture store",
		image: image31,
		category: "Other",
		saved: false,
		address: "Čerkez Mahala bb, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.14177421024154, 20.523183469070844],
		name: "DEICHMANN",
		text: "Shoe store",
		image: image32,
		category: "Other",
		saved: false,
		address: "Čerkez Mahala bb, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.14123906995905, 20.522696861798803],
		name: "Dallas Namestaj",
		text: "Furniture store",
		image: image33,
		category: "Other",
		saved: false,
		address: "Čerkez Mahala bb, Novi Pazar 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.155641561211674, 20.55000021640059],
		name: "Hotel Emrović Raj",
		text: "Hotel",
		image: image34,
		category: "Hotel",
		saved: false,
		address: "BANJA 72, Нови Пазар 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.1561928145815, 20.54952550425464],
		name: "Aqua Spa Termale Novi Pazar",
		text: "Aqua Spa",
		image: image35,
		category: "Other",
		saved: false,
		address: "Novopazarska bb, Banja 36300",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.157457851591104, 20.54668691938193],
		name: "Stara Novopazarska Banja",
		text: "Banja",
		image: image36,
		category: "Culture",
		saved: false,
		address: "Banja",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
	{
		location: [43.15544595801543, 20.53120939565306],
		name: "Youmart Novi Pazar",
		text: "Shopping mall",
		image: image37,
		category: "Other",
		saved: false,
		address: "Dimitrija Tucovića bb, Novi Pazar",
		about: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat ipsa iure culpa eum delectus porro. Vero explicabo recusandae et neque accusantium veniam aperiam a, nemo repudiandae necessitatibus quibusdam fugit iure?",
	},
];
